<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// maunche

$charge = array (

  'patterns' => array (
  'maunches?',
  ),

  'doc' => 'Stuff...',

  'width' => 280.07498,
  'height' => 291.82971,
  'body' => '<path stroke-width="2" stroke="#000000" d="M 30.8,1 C 77.1,29.5 129,89.7 141,97.7 162,84.7 168,64.7 263,3.8 244,23.8 252,97.7 252,133 221,161 175,190 146,192 87.1,192 52.9,87.7 47.2,86.7 36.5,119 68.7,188 60.8,225 59.4,320 -5.6,306 1.5,225 6.5,173 16.5,164 14.4,111 13.7,29.5 12.2,5.3 30.8,1 z" />
          <path stroke="#000000" stroke-width="2" fill="#333333" d="m 263,6 c 23,-20 15,87.7 13,125 -2,51 -22,51 -20,84 3,33 -1,55 0,52 2,-3 -24,-71 -14,-84 10,-12 11,-40 10,-53 C 246,18.8 261,6 263,6 z" />
          <path stroke="#000000" stroke-width="2" fill="#666666" d="M 27.9,20.3 C 25.1,33.8 19.4,97.7 24.4,146 22.9,166 4.4,255 27.2,268 44.7,274 52,222 34.4,138 42.5,90.7 27.2,18.8 27.9,20.3 z" /> ',

)

?>
