<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// addice

$charge = array (

  'patterns' => array (
  'addices?',
  'carpenters? axes?',
  ),

  'doc' => 'Stuff...',

  'height' => 1052,
  'width' => 744,
  'orient_to_ordinary' => true,
  'hflex' => 1.4,
  'wflex' => 1.2,
  'body' => '<g />',
  'features' => 
  array (
    'handle' => 
    array (
      'body' => '<path  stroke="#000000" stroke-width="6" d="m 564.9,10.25 c 0,0 -8.3,-15.848 -52,0.68 C 477.1,184.3 626.4,192.8 572,396.4 517.6,600 555.9,657.8 537.8,729 514.3,825.5 387.1,952.9 328,963.8 339.3,1010 374.9,1061 427.5,1045 475.7,1009 621.7,957.7 631.1,729 636.2,605.9 597.7,484.8 662.2,279.8 661.6,175.7 569.5,17.48 564.9,10.25 z" /> ',
    ),
    'blade' => 
    array (
      'body' => '<path stroke="#000000" stroke-width="6" d="M 510.3,73.08 15.54,225.4 410.4,273.6 738.4,108.8 c 0,0 -3,10.3 0,0 6.2,-83.93 -5.7,-79.34 -10.4,-77.79 -4.6,1.56 -132.5,31.19 -132.5,31.19 0,0 9.9,31.6 2.6,47.8 -8.5,19 -89.5,48.5 -86.5,-9.2 -2.6,-9.84 0.2,-26.17 -1.3,-27.72 z" /> 
           <path stroke="#000000" stroke-width="6" d="M 725.44,30.14 C 722.14,44.43 727.64,79.6 727.64,79.6 L 406.68,275.25" />',
    ),
  ),

)

?>
