<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/bbox.svg',
'patterns' => array (
  0 => '?bounding box(es)?',
),
'wflex' => 999,
'hflex' => 999,
'orient_to_ordinary' => true,
);
