<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/lozenge.svg',
  'link' => 'http://karlwilcox.com/parker/l/lozenge',
'patterns' => array (
  0 => 'lozenges?',
),
'hflex' => 1.2,
'wflex' => 1.2,
'orient_to_ordinary' => true,
);
