<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/triangle.svg',
  'link' => 'http://karlwilcox.com/parker/t/triangle',
'patterns' => array (
  0 => 'triangles?',
),
'modifiers' => array (
  0 => 
  array (
    0 => NULL,
    1 => 'voided',
    2 => 'mod',
    3 => 'voided',
  ),
),
'orient_to_ordinary' => true,
);
