<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// goutte

$charge = array (

  'patterns' => array (
  'go?uttes?',
  ),

  'doc' => 'Stuff...',

  'width' => 150,
  'height' => 400,
  'body' => '<path stroke="#000000" stroke-width="4" d="M 80,2.1 C 80,2.1 45,54 48,82 c 3,28 14,68 6,148 -3,20 -29,40 -40,60 -16,30 -19.7,100 36,110 60,10 100,-30 100,-60 C 170,240 110,220 100,200 92,140 70,69 83,42 87,33 82,4.3 80,2.1 z" />
             <path stroke="none" opacity="0.6" fill="#4D4D4D" d="M 80,2.1 C 80,2.1 66,48 65,79 c -1,31 5,81 15,111 9,30 60,50 40,140 -35,70 -125.7,60 -70,70 60,10 100,-40 100,-60 C 180,240 110,230 100,200 85,140 83,90 83,42 83,32 82,4.3 80,2.1 z" />',
  'orient_to_ordinary' => true,

)

?>
