<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/paschal-lamb.svg',
  'link' => 'http://karlwilcox.com/parker/p/paschal-lamb',
'patterns' => array (
  0 => 'paschal lambs?',
  1 => 'lambs? of god',
  2 => 'agnus dei',
  3 => 'holy lambs?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'ungled',
    1 => 'ungled',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => 'banner',
    1 => 'banner',
    2 => 'feature',
  ),
),
);
