<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/tiger.svg',
  'link' => 'http://karlwilcox.com/parker/t/tiger',
'patterns' => array (
  0 => 't(i|y)gers?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'armed',
    1 => 'armed',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => 'tongued',
    1 => '(ton|lan)gued',
    2 => 'feature',
  ),
),
'demi' => 'horizontal',
);
