<?php /* Copyright 2011 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// hawk

$charge = array (
 'patterns' => array (
    'hawks? bells?',
  ),
  'height' => 400, 'width' => 344,
        'body' => '
        <path stroke="inherit" stroke-width="4" d="m 186,400 -1,-115 c 61,-61 -79,-67 -23,0 l 2,114 C 164,399 3.23,389 1.43,233 -0.373,77.7 127,58.6 185,59.3 243,60 341,111 344,236 347,361 186,400 186,400 z" />
        <path stroke="inherit" stroke-width="4" d="M 2.86,205 341,205" />
        <path stroke="inherit" stroke-width="4" d="M 2.14,224 341,224" />
        <path stroke="inherit" stroke-width="4" d="M 117,65 C 99.3,45 90,1.43 161,1.43 c 70,0 81,43.57 57,62.17 -14,-2.2 -18,-2.2 -18,-2.2 0,0 17,-22.8 -1,-33.6 -5,-7.1 -65,-10.7 -73,-0.7 -10,14.3 8,34.3 8,34.3 z" />
      ',
);
?>
