<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// anvil

$charge = array (

  'patterns' => array (
  '?smiths anvil',
  ),

  'doc' => 'Stuff...',

  'height' => '400',
  'width' => '400',
  'body' => '
      <path stroke="#000000" stroke-width="2" d="m 390,21 0,63 -150,76 0,-60 150,-79 z" />
      <path stroke="#000000" stroke-width="2" d="m 9.1,100 -3,70 233.9,0 0,-72" />
      <path fill="#4d4d4d" stroke="none" d="m 390,21 0,63 -150,76 0,-60 150,-79 z" />
      <path stroke="#000000" stroke-width="2" d="M 8.1,100 140,18 390,20 c 0,0 -30,17 -60,33 10,22 70,24 70,24 l -120,4 -40,19 -231.9,0 z" />
      <path stroke="#000000" stroke-width="2" d="m 160,390 20,-20 c 0,0 10,-190 220,-291 0,0 -230,111 -230,111" />
      <path stroke="#000000" stroke-width="2" d="M 6.1,170 C 100,200 120,300 120,390 c 20,0 40,0 40,0 10,-100 20,-170 70,-230" />
      <path stroke="#000000" stroke-width="2" d="m 110,280 70,0" />
      <path fill="#333333" stroke="none" d="m 160,390 20,-20 c 0,0 10,-180 190,-274 -100,44 -140,64 -140,64 0,0 -60,60 -70,230" />
      ',

)

?>
