<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/barrel.svg',
  'link' => 'http://karlwilcox.com/parker/b/barrel',
'patterns' => array (
  0 => 'barrels?',
  1 => 'tu(b|n)s?',
  2 => 'hogsheads?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'hooped',
    1 => 'hooped',
    2 => 'feature',
  ),
),
);
