<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/chevroncouched.svg',
'patterns' => array (
  0 => 'chevron(el)?s? couched',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'sinister',
    1 => 'sinister',
    2 => 'mod',
    3 => 'direction',
  ),
  1 => 
  array (
    0 => 'dexter',
    1 => 'dexter',
    2 => 'mod',
    3 => 'direction',
  ),
),
'either' => array (
  0 => 'chevron',
),
'wflex' => 2,
'hflex' => 2,
);
