<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/crescent.svg',
  'link' => 'http://karlwilcox.com/parker/c/crescent',
'patterns' => array (
  0 => 'crescents?',
),
'modifiers' => array (
  0 => 
  array (
    0 => NULL,
    1 => 'pendent',
    2 => 'mod',
    3 => 'inverted',
  ),
),
'wflex' => 2,
'hflex' => 2,
'orient_to_ordinary' => true,
);
