<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/delf.svg',
  'link' => 'http://karlwilcox.com/parker/d/delf',
'patterns' => array (
  0 => 'delf',
  1 => 'delves',
  2 => 'blocks?',
  3 => 'gads?',
  4 => 'cubes?',
),
'orient_to_ordinary' => true,
);
