<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/escutcheon.svg',
  'link' => 'http://karlwilcox.com/parker/e/escutcheon',
'patterns' => array (
  0 => 'escut?cheons?',
),
'modifiers' => array (
  0 => 
  array (
    0 => NULL,
    1 => 'of pretence',
    2 => 'ignore',
  ),
  1 => 
  array (
    0 => 'subshield',
    1 => 'of !pretence',
    2 => 'shieldmod',
  ),
),
'orient_to_ordinary' => true,
);
