<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/fret.svg',
  'link' => 'http://karlwilcox.com/parker/f/fret',
'patterns' => array (
  0 => 'frets?',
),
'either' => array (
  0 => 'subordinary',
  1 => 'geometric',
),
'orient_to_ordinary' => true,
);
