<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// water-bouget

$charge = array (

  'patterns' => array (
  '?water bougets?',
  ),

  'doc' => 'Stuff...',

  'width' => 332,
  'height' => 243,
  'body' => '<path stroke="#000000" stroke-width="4" d="M 51.2,94 C 71.9,84 158,85 170,85 c 13,0 110,7 117,12 10,8 25,22 -30,48 -9,-11 -51,-36 -89,-36 -38,1 -33,-11 -86.5,32 C 42.1,111 51.2,94 51.2,94 z" />
     <path stroke="#000000" stroke-width="4" d="m 166,47 c 26,5 30,-25 53,-17 4,34 -27,31 -34,120 -1,22 38,115 110,88 71,-27 17,-115 7,-91 -27,64 -72,43 -81,12 C 202,94.7 242,44 260,23 260,23 187,-4 166,2 145,-4 72.1,23 72.1,23 91.1,44 130,94.7 112,159 103,190 57.1,211 30.1,147 20.3,123 -34,211 37.1,238 110,265 149,172 147,150 141,61 110,64 113,30 c 23,-8 27,22 53,17 z" />',

)

?>
