<?php

$charge['modifiers'][] = array ( 'erased', 'erased', 'mod', 'neckline' );
$charge['modifiers'][] = array ( 'couped', 'couped', 'mod', 'neckline' );
$charge['modifiers'][] = array ( 'couped-fitchy', 'couped fitchy', 'mod', 'neckline' );
$charge['modifiers'][] = array ( 'caboshed', '(c|k)abo(c|s)(h|s)ed', 'mod', 'neckline' );
$charge['modifiers'][] = array ( 'caboshed', 'trunked', 'mod', 'neckline' );

?>