<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// scallop

$charge = array (

  'patterns' => array (
  'e?scallops?',
  ),

  'doc' => 'Stuff...',

  'width' => 650,
  'height' => 750,
  'body' => '<g fill-rule="evenodd" stroke="#000000" stroke-width="12" ><path d="m 300,610 c 30,30 60,0 60,-60 30,30 150,30 150,-60 30,-30 90,-30 30,-150 30,0 60,-90 0,-120 C 270,160 390,-19 300,11 210,-19 330,160 26,220 c -30.5,30 0,120 0,120 -60,120 30,120 60,150 0,90 124,90 124,60 30,60 60,90 90,60 z"  />
  <path d="M 230,110 C 200,91 180,33 150,53 c -54,38 -10,127 10,137 20,10 80,-70 70,-80 z"  />
  <path d="M 35,340 150,300"  />
  <path d="m 77,490 63,-60"   />
  <path d="m 220,580 20,-60"  />
  <path d="m 360,100 c 30,-29 60,-89 60,-59 60,30 30,119 0,149 0,0 -60,-90 -60,-90 z" />
  <path d="M 540,340 450,280"  />
  <path d="M 510,490 450,400"  />
  <path d="m 360,550 0,-60"  />
</g>',
  'demi' => 'horizontal',

)

?>
