<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/heart.svg',
  'link' => 'http://karlwilcox.com/parker/h/heart',
'patterns' => array (
  0 => '?human hearts?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'flammant',
    1 => 'flammant',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => 'flammant',
    1 => 'emitting flames of fire',
    2 => 'feature',
  ),
  2 => 
  array (
    0 => 'crowned',
    1 => '?imperially crowned',
    2 => 'feature',
  ),
),
'proper' => rgb('gules'),
'orient_to_ordinary' => true,
'hflex' => 1.2,
'wflex' => 1.6,
);
