<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/chough.svg',
  'link' => 'http://karlwilcox.com/parker/c/chough',
'patterns' => array (
  0 => '?cornish choughs?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'legged',
    1 => 'legged',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => 'beaked',
    1 => 'beaked',
    2 => 'feature',
  ),
),
'proper' => rgb('sable'),
'orient_to_ordinary' => true,
);
