<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// martlett

$charge = array (

  'patterns' => array (
  'martlett?s?',
  ),

  'doc' => 'Stuff...',

  'width' => 500,
  'height' => 350,
  'body' => '<g stroke="#000000" stroke-width="4">
   <path d="M 75,1.5 C 45,6 35,6.1 41,52 c 11,4 31,16 29,98 50,60 110,30 110,40 20,30 0,50 -30,80 30,-20 40,-20 40,-20 20,20 30,30 60,30 -20,-20 -60,-50 -10,-80 80,50 40,10 190,150 C 410,250 360,240 320,200 420,230 420,240 490,220 400,190 350,190 320,160 380,140 390,140 390,140 330,140 260,130 220,100 200,89 160,65 140,55 82,-10 74,0.76 75,1.5 z" />
   <path d="m 78,30 a 9.1,8.7 0 1 1 -18,0 9.1,8.7 0 1 1 18,0 z" />
   <path d="M 40,20 C 34,22 1.5,35 1.5,35 L 39,51" />
   <path d="m 130,70 c -20,14 -40,80 40,90 120,0 160,0 160,-10" />
   <path d="m 120,190 c -10,30 -45,40 -54,50 -9,0 54,10 64,-10 10,20 20,30 20,30 0,-30 -10,-70 0,-70" />
   </g>',

)

?>
