<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// antique

$charge = array (

  'patterns' => array (
  'saxon crowns?',
  ),

  'doc' => 'Stuff...',

  'wflex' => 1.5,
  'hflex' => 1.2,
  'height' => 190, 'width' => 400,
    'body' => '
      <path stroke="inherit" stroke-width="2" d="M 385,62.6 328,130 320,105 375,55.5" />
      <path stroke="inherit" stroke-width="2" d="m 186,114 c 0,0 13,-24.3 18,-30.2 14,-15.6 118,12.2 120,22.2 3,9 4,29 4,29" />
      <path stroke="inherit" stroke-width="2" d="M 29.3,52.5 84.8,105 73.7,135 20.2,57.6 l -1,0" />
      <path stroke="inherit" stroke-width="2" d="M 73.7,146 83.8,106 C 107,86.4 178,70.7 188,83.8 l 4,30.2" />
      <path stroke="inherit" stroke-width="2" d="M 29.3,48 A 14.1,12.6 0 1 1 1.1,48 14.1,12.6 0 1 1 29.3,48 z" />
      <path stroke="inherit" stroke-width="2" d="m 398,48.5 a 11.6,12.1 0 1 1 -24,0 11.6,12.1 0 1 1 24,0 z" />
      <path stroke="inherit" stroke-width="2" d="m 211,14.1 a 13.6,13.1 0 1 1 -28,0 13.6,13.1 0 1 1 28,0 z" />
      <path stroke="inherit" stroke-width="2" d="M 74.7,146 C 84.9,111 319,104 330,136 350,195 58.9,200 74.7,146 z" />
      <path fill="#000000" fill-opacity="0.423" stroke="inherit" stroke-width="2" d="m 104,149 c 0,-27 207,-21 210,-9 6,25 -210,36 -210,9 z" />
      <path stroke="inherit" stroke-width="2" d="m 190,26.2 c -1,5.1 -10,74.8 -10,74.8 0,0 5,11 29,3 3,-1 -6,-76.7 -6,-76.7 z" />
      <path fill="none" stroke="inherit" stroke-width="2" d="M 177,92 C 142,88.9 83.8,115 75.7,126" />
      <path fill="none" stroke="inherit" stroke-width="2" d="M 321,118 C 304,104 222,86.9 210,88.9" />
      ',
);

?>
