<?php /* Copyright 2011 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// church

$charge = array (
 'patterns' => array (
    '?(church|war) bells?',
  ),
  'width' => 264,
  'height' => 434,
  'body' => '
        <path stroke="inherit" stroke-width="4" d="M 69.5,61.6 C 87.5,43.4 202,35.4 218,59.6 218,59.6 226,167 264,305 238,363 30.1,359 5.04,303 55.2,168 69.5,61.6 69.5,61.6 z" />
        <path stroke="inherit" stroke-width="4" d="M 4.04,302 C 35.4,281 225,270 263,304" />
        <path stroke="inherit" stroke-width="4" d="M 21.3,256 C 63.7,243 252,240 254,266" />
        <path stroke="inherit" stroke-width="4" d="m 93.9,49.5 c 0,0 -13.1,-33.3 -4,-39.4 23.1,-13.13 115.1,-8.08 118.1,0 8,6.1 -6,38.4 -6,38.4 -10,-1 -25,-4.1 -25,-4.1 0,0 5,-14.5 3,-18.2 -7,-14.1 -61,-9.1 -70,-1 l 7,22.3 z" />
        <path fill="#000000" fill-opacity="0.614" stroke="inherit" stroke-width="4" d="M 4.04,303 C 47.5,278 253,273 261,306 269,339 70.7,377 2.02,307" />
        <path stroke="inherit" stroke-width="4" d="m 163,298 c 0,9 -14,16 -31,16 -17,0 -31,-7 -31,-16 0,-9 14,-16 31,-16 17,0 31,7 31,16 z" />
      ',
);
?>
