<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/hurt.svg',
  'link' => 'http://karlwilcox.com/parker/h/hurt',
'patterns' => array (
  0 => 'hurts?',
),
'flags' => array (
  'always_proper' => true,
),
'proper' => rgb('azure'),
);
