<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/pellet.svg',
  'link' => 'http://karlwilcox.com/parker/p/pellet',
'patterns' => array (
  0 => 'pellets?',
  1 => 'gunstones?',
  2 => 'ogress(es)?',
),
'flags' => array (
  'always_proper' => true,
),
'proper' => rgb('sable'),
);
