<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/rainbow.svg',
  'link' => 'http://karlwilcox.com/parker/r/rainbow',
'patterns' => array (
  0 => 'rainbows?',
),
'turn_on_fesswise' => false,
'turn_on_palewise' => false,
'orient_to_ordinary' => false,
'hflex' => 999,
'wflex' => 999,
);
