<?php

$ordinary['modifiers'][] = array ( 'both', '(couped|humetty|alese)', 'mod', 'couped' );
$ordinary['modifiers'][] = array ( 'sinister', '(couped|humetty|alese) ?in sinister', 'mod', 'couped' );
$ordinary['modifiers'][] = array ( 'dexter', '(couped|humetty|alese) ?in dexter', 'mod', 'couped' );
$ordinary['modifiers'][] = array ( 'chief', '(couped|humetty|alese) ?in chief', 'mod', 'couped' );
$ordinary['modifiers'][] = array ( 'base', '(couped|humetty|alese) ?in base', 'mod', 'couped' );

?>