<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/peacock.svg',
  'link' => 'http://karlwilcox.com/parker/p/peacock',
'patterns' => array (
  0 => 'peacocks?',
),
'modifiers' => array (
  0 => 
  array (
    0 => NULL,
    1 => 'in (his|their) pride',
    2 => 'ignore',
  ),
  1 => 
  array (
    0 => 'taileyes',
    1 => '?the eyes of ?the tail',
    2 => 'feature',
  ),
),
'proper' => rgb('vert'),
'orient_to_ordinary' => 1,
);
