<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// rainbow

$charge = array (

  'patterns' => array (
  'rainbows?',
  ),

  'doc' => 'Stuff...',

  'width' => 500,
  'height' => 200,
  'turn_on_fesswise' => false,
  'turn_on_palewise' => false,
  'orient_to_ordinary' => false,
  'body' => '<path fill="#efd807" d="M 0.732,200 C 0.732,200 88.6,-0.741 250,0.732 411,2.2 503,200 503,200 l -52,0 C 451,200 340,27.8 250,27.8 158,27.8 52.4,200 52.4,200 l -51.668,0 z" />
                   <path fill="#e21313" d="M 51,200 C 51,200 127,27.8 250,27.1 372,26.3 453,200 453,200 l -52,0 C 401,200 330,56.3 250,57.8 169,59.3 103,200 103,200 l -52,0 z" />
                   <path fill="#149414" d="M 101,200 C 101,200 165,57.9 250,57.1 334,56.3 402,200 402,200 l -52,0 C 350,200 305,87 250,87.8 194,88.6 153,200 153,200 l -52,0 z" />
                   <path fill="#fofofo" d="M 152,200 C 152,200 182,87.9 250,87.1 317,86.3 352,200 352,200 l -52,0 c 0,0 -3,-82 -50,-82 -46,0 -46,82 -46,82 l -52,0 z" />',
  'hflex' => 999,
  'wflex' => 999,

)

?>
