<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/rose.svg',
  'link' => 'http://karlwilcox.com/parker/r/rose',
'patterns' => array (
  0 => 'roses?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'barbed',
    1 => 'barbed',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => 'seeded',
    1 => 'seeded',
    2 => 'feature',
  ),
),
'proper' => 'argent',
);
