<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/vine-leaf.svg',
'patterns' => array (
  0 => 'vine leaf',
  1 => 'vine leaves',
),
'orient_to_ordinary' => true,
'hflex' => 1.3,
'wflex' => 1.3,
'proper' => rgb('vert'),
);
