<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/vine.svg',
  'link' => 'http://karlwilcox.com/parker/v/vine',
'patterns' => array (
  0 => 'vines?',
),
'orient_to_ordinary' => true,
'hflex' => 1.2,
'wflex' => 1.2,
'modifiers' => array (
  0 => 
  array (
    0 => 'stick',
    1 => '?the ?vine stick',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => 'leaves',
    1 => 'leave[sd]',
    2 => 'feature',
  ),
  2 => 
  array (
    0 => 'fruits',
    1 => 'fructed',
    2 => 'feature',
  ),
),
'proper' => rgb('vert'),
);
