<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/boars-head.svg',
'patterns' => array (
  0 => 'boars? heads?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'armed',
    1 => 'armed',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => NULL,
    1 => 'couped',
    2 => 'ignore',
  ),
),
'demi' => 'horizontal',
);
