<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/cow.svg',
  'link' => 'http://karlwilcox.com/parker/c/cow',
'patterns' => array (
  0 => 'cows?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'horned',
    1 => 'horned ?and ?belled',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => 'collared',
    1 => 'collared ?and ?belled',
    2 => 'feature',
  ),
),
);
