<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/ram.svg',
  'link' => 'http://karlwilcox.com/parker/r/ram',
'patterns' => array (
  0 => 'rams?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'armed',
    1 => 'armed',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => 'armed',
    1 => '(u|o)nguled',
    2 => 'feature',
  ),
  2 => 
  array (
    0 => NULL,
    1 => 'statant',
    2 => 'ignore',
  ),
  3 => 
  array (
    0 => NULL,
    1 => 'rampant',
    2 => 'ignore',
  ),
  4 => 
  array (
    0 => NULL,
    1 => 'passant',
    2 => 'ignore',
  ),
),
);
