<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/wolf-head.svg',
'patterns' => array (
  0 => 'wolfs? heads?',
  1 => 'wolves heads?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'eyes',
    1 => 'eyes',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => 'erased',
    1 => 'erased',
    2 => 'mod',
    3 => 'neckline',
  ),
  2 => 
  array (
    0 => 'couped',
    1 => 'couped',
    2 => 'mod',
    3 => 'neckline',
  ),
  3 => 
  array (
    0 => 'couped-fitchy',
    1 => 'couped fitchy',
    2 => 'mod',
    3 => 'neckline',
  ),
  4 => 
  array (
    0 => 'caboshed',
    1 => '(c|k)abo(c|s)(h|s)ed',
    2 => 'mod',
    3 => 'neckline',
  ),
  5 => 
  array (
    0 => 'caboshed',
    1 => 'trunked',
    2 => 'mod',
    3 => 'neckline',
  ),
),
);
