<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/salmon.svg',
  'link' => 'http://karlwilcox.com/parker/s/salmon',
'patterns' => array (
  0 => 'salmon',
  1 => 'trout',
),
'modifiers' => array (
  0 => 
  array (
    0 => NULL,
    1 => 'hauriant ',
    2 => 'ignore',
  ),
  1 => 
  array (
    0 => NULL,
    1 => 'finned',
    2 => 'ignore',
  ),
),
);
