<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/caltrap.svg',
  'link' => 'http://karlwilcox.com/parker/c/caltrap',
'patterns' => array (
  0 => '(g|c)altraps?',
  1 => 'cheval traps?',
),
'orient_to_ordinary' => true,
);
