<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/pheon.svg',
  'link' => 'http://karlwilcox.com/parker/p/pheon',
'patterns' => array (
  0 => 'arrow heads?',
  1 => '(f|ph)eons? ?heads?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'up',
    1 => 'points? upwards?',
    2 => 'mod',
    3 => 'pointing',
  ),
  1 => 
  array (
    0 => 'down',
    1 => 'points? downwards?',
    2 => 'mod',
    3 => 'pointing',
  ),
),
'orient_to_ordinary' => true,
);
