<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// pheon

$charge = array (

  'patterns' => array (
  'arrow heads?',
  ),
  'modifiers' => array (
    array ( 'up', 'points? upwards?', 'mod', 'pointing',    ),
    array ( 'down', 'points? downwards?', 'mod', 'pointing',    ),
  ),

  'doc' => 'Stuff...',

  'width' => 336,
  'height' => 417,
  'body' => '<path d="m 137,164 25,173 36,-171 -61,-2 z" stroke="#000000" stroke-width="2" />
      <path d="m 214,154 a 46,13.5 0 0 1 -92,0 46,13.5 0 1 1 92,0 z" stroke="#000000" stroke-width="2" />
      <path d="m 211,130 a 42.2,24.7 0 1 1 -84,0 42.2,24.7 0 1 1 84,0 z" stroke="#000000" stroke-width="2" />
      <path d="m 117,83.1 c 1,18.9 24,39.9 55,37.9 41,-3 43,-22.2 52,-36.8 10,-15.5 -106,-0.6 -107,-1.1 z" stroke="#000000" stroke-width="2" />
      <path d="m 238,64.5 a 69.5,27.8 0 0 1 -138.7,0 69.5,27.8 0 1 1 138.7,0 z" stroke="#000000" stroke-width="2" />
      <path d="m 213,63.2 a 48,12.4 0 0 1 -96,0 48,12.4 0 1 1 96,0 z"  stroke="#000000" stroke-width="2" />
      <path d="m 105,162 c 2,15 -14.1,21 12,48 -8,18 -13,22 13,47 -17,15 6,43 15,40 -3,36 42,33 37,-1 33,-6 28,-25 23,-38 23,-18 21,-30 17,-51 34,-39 13,-41 18,-44 10,-7 70,0 70,0 L 163,385 28.3,161 105,162 z" stroke="#000000" stroke-width="2" />
      <path d="M 190,174 166,297"  fill="none" stroke="#000000" stroke-width="2" />
      <path d="M 182,177 165,282"  fill="none" stroke="#000000" stroke-width="2" />
      <path d="m 175,178 -7,58"  fill="none" stroke="#000000" stroke-width="2" />
      <path d="M 39.9,171 132,321"  fill="none" stroke="#000000" stroke-width="2" />
      <path d="m 50,171 77,127"  fill="none" stroke="#000000" stroke-width="2" />
      <path d="M 59.1,171 116,265"  fill="none" stroke="#000000" stroke-width="2" />
      <path d="M 70.2,173 100,225"  fill="none" stroke="#000000" stroke-width="2" />
      <path d="M 80.3,173 102,212"  fill="none" stroke="#000000" stroke-width="2" />
      <path d="M 293,169 201,319"  fill="none" stroke="#000000" stroke-width="2" />
      <path d="M 283,169 206,296"  fill="none" stroke="#000000" stroke-width="2" />
      <path d="m 274,169 -57,94"  fill="none" stroke="#000000" stroke-width="2" />
      <path d="m 263,170 -30,53"  fill="none" stroke="#000000" stroke-width="2" />
      <path d="m 253,170 -22,40"  fill="none" stroke="#000000" stroke-width="2" />',
  'orient_to_ordinary' => true,

)

?>
