<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/cramp.svg',
  'link' => 'http://karlwilcox.com/parker/c/cramp',
'patterns' => array (
  0 => 'cramp(oon)?s?',
  1 => 'cramp iron',
  2 => 'crampiron',
),
);
