<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/salamander.svg',
  'link' => 'http://karlwilcox.com/parker/s/salamander',
'patterns' => array (
  0 => 'salamander',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'enflamed',
    1 => 'enflamed',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => 'enflamed',
    1 => 'in a (flame|fire)',
    2 => 'feature',
  ),
  2 => 
  array (
    0 => 'crowned',
    1 => 'crowned',
    2 => 'feature',
  ),
),
'proper' => rgb('gules'),
);
