<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/cross.svg',
  'link' => 'http://karlwilcox.com/parker/c/cross',
'patterns' => array (
  0 => '?plain cross(es)? ?passant',
),
'either' => array (
  0 => 'cross',
  1 => 'cross',
),
);
