<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/tau.svg',
  'link' => 'http://karlwilcox.com/parker/t/tau',
'patterns' => array (
  0 => 'tau ?cross(es)?',
  1 => 'cross(es)? ?of (saint|st) anthony',
  2 => 'cross(es)? tau',
),
'either' => array (
  0 => 'cross',
),
);
