<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// dove

$charge = array (

  'patterns' => array (
  'doves?',
  ),

  'doc' => 'Stuff...',

  'width' => 272,
  'height' => 275,
  'proper' => '#faebd7',
  'body' => '<path style="stroke:#000000;stroke-width:6;stroke-miterlimit:4;" d="M 80,8.6 C 61,23 51,20 76,74 c 16,36 -31,56 -16,96 8,30 40,50 60,50 30,0 160,20 150,-30 C 250,170 220,180 240,160 190,160 140,120 130,98 150,14 98,-1 80,8.6 z"/>
   <path style="fill:#000000;stroke:#000000;stroke-width:6;stroke-miterlimit:4;" d="m 90,31 a 7.3,6.2 0 1 1 -14,0 7.3,6.2 0 1 1 14,0 z"/>
   <path style="fill:#000000;stroke:#000000;stroke-width:6;stroke-miterlimit:4;" d="m 110,220 c 10,40 -11,50 -28,50 14,10 38,0 38,0 0,0 -10,0 0,-20 10,-20 10,-20 10,-30 0,0 -10,0 -20,0 z m 40,-10 c 0,10 0,20 0,30 0,20 -10,20 -20,30 0,0 30,0 40,0 -10,-10 -30,-10 -20,-10 0,0 20,-30 30,-40 10,0 -30,-10 -30,-10 z M 64,23 15,39 67,58 64,23 z"/>
   <path style="fill:none;stroke:#000000;stroke-width:6;stroke-miterlimit:4;" d="m 200,190 c 40,20 70,10 70,10 M 110,140 c -12,30 20,60 130,20"/>',

)

?>
