<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/mermaid.svg',
  'link' => 'http://karlwilcox.com/parker/m/mermaid',
'patterns' => array (
  0 => 'mermaids?',
  1 => 'sirens?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'hair',
    1 => 'crined',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => 'mirror',
    1 => '?holding ?a mirror ?in ?(her|the|their) ?(right|left) ?hand ',
    2 => 'feature',
  ),
  2 => 
  array (
    0 => 'comb',
    1 => '?holding ?a comb ?in ?(her|the|their) ?(right|left) ?hand ',
    2 => 'feature',
  ),
),
);
