<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/phoenix.svg',
  'link' => 'http://karlwilcox.com/parker/p/phoenix',
'patterns' => array (
  0 => 'phoenixe?s?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'langued',
    1 => 'langued',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => 'beaked',
    1 => 'beaked',
    2 => 'feature',
  ),
  2 => 
  array (
    0 => 'enflamed',
    1 => 'enflamed',
    2 => 'feature',
  ),
  3 => 
  array (
    0 => 'enflamed',
    1 => 'in flames',
    2 => 'feature',
  ),
),
'proper' => rgb('argent'),
);
