<?php /* Copyright 2011 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */

// chessrook

$charge = array (
 'patterns' => array (
    'chessrooks?',
    'cockes?',
  ),
  'height' => 400, 'width' => 400,
    'body' => '
      <path stroke="inherit" stroke-width="4" d="M 3.03,341 C 201,247 106,17.8 1.01,110 29.3,11.1 63.2,-5.6 115,2 171,10.3 200,150 200,150 200,150 239,5.44 298,0.99 349,-2.85 375,22.2 401,116 281,34.6 231,253 402,343" />
      <path stroke="inherit" stroke-width="4" d="m 112,192 187,0 c 3,0 5,2 5,5 l 0,24 c 0,3 -2,5 -5,5 l -187,0 c -3,0 -5,-2 -5,-5 l 0,-24 c 0,-3 2,-5 5,-5 z" />
      ',
  
  );
?>
