<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/scythe.svg',
  'link' => 'http://karlwilcox.com/parker/s/scythe',
'patterns' => array (
  0 => 'scythes?',
),
  'modifiers' => array (
    array ( 'handle', '?the handle[sd]?', 'feature', ),
  ),
'orient_to_ordinary' => true,
'hflex' => 1.2,
'wflex' => 1.2,
'turn_on_fesswise' => true,
);
