<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/firtree.svg',
'patterns' => array (
  0 => '(pine|fir) trees?',
),
'modifiers' => array (
  0 => 
  array (
    0 => NULL,
    1 => 'fructed',
    2 => 'ignore',
  ),
  1 => 
  array (
    0 => NULL,
    1 => 'erased',
    2 => 'ignore',
  ),
),
);
