<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 12/08/14
 * Time: 18:50
 */

$charge = array(
'file' => 'inkscape/thistle.svg',
  'link' => 'http://karlwilcox.com/parker/t/thistle',
'patterns' => array (
  0 => 'thistles?',
),
'modifiers' => array (
  0 => 
  array (
    0 => 'slipped',
    1 => 'slipped',
    2 => 'feature',
  ),
  1 => 
  array (
    0 => 'leaved',
    1 => 'leaved',
    2 => 'feature',
  ),
),
'proper' => array( 'body' => rgb('vert'), 'leaved' => rgb('vert'), 'slipped' => rgb('purpure') ),
'orient_to_ordinary' => true,
'hflex' => 1.4,
'wflex' => 1.2,
);
